### ISSUE TITLE
Add useful guide to start the project locally

### ISSUE THREAD

**Issue by agilecreativity** [tatut/clj-chrome-devtools#4]
Thanks for a great library:

I have one suggestion that might be useful for someone to get started with the project:

```sh
git clone https://github.com/tatut/clj-chrome-devtools.git
cd clj-chrome-devtools
git submodule init
git submodule update
# then follow the guide in the README to start the REPL
# e.g. 
lein repl 
# or 
lein test
```

**Comment by tatut** [comment]
I didn't think about that, I just assumed people would use this as a leiningen dependency.

Perhaps we should have some sort of quick start guide in the gh pages and possibly the README. 
I'm not certain what form of documentation would be the most helpful, but PRs are certainly welcome.

Another thing that could be useful is an examples folder with a couple of simple projects, like an example e2e test and some screen scraping example.

**Comment by eerohele** [comment]
I whipped up a quick [screen scraping example project](https://github.com/eerohele/clj-chrome-devtools/commit/767f2ded2330c4b2d5038fd89a0808b190588068) while figuring out how to get started with this library, but to be honest, it's practically identical to [`chrome_test.clj`](https://github.com/tatut/clj-chrome-devtools/blob/802c72aeacaebf4f671ed4bc0cff7bc8663e477b/test/clj_chrome_devtools/chrome_test.clj).

Still, if you want the PR, just let me know.

A couple of unrelated things I noticed while working on the example project:

- Is [this println](https://github.com/tatut/clj-chrome-devtools/blob/802c72aeacaebf4f671ed4bc0cff7bc8663e477b/src/clj_chrome_devtools/automation.clj#L96) intentional? It adds quite a bit of noise into the test output.
- It might be nice if `to` also accepted `java.net.URI` (and maybe `java.net.URL`) in addition to a string.

**Comment by tatut** [comment]
I don't think we need the example, if it's same as the test we currently have.

But I'll gladly take a PR to remove the vestigial println and add URI/URL support for `to`.

**Comment by eerohele** [comment]
>I don't think we need the example, if it's same as the test we currently have.

Makes sense. Maybe the README could point to the unit tests, though? I certainly found them very useful.

>But I'll gladly take a PR to remove the vestigial println and add URI/URL support for to.

OK, I'll see if I can take a look.

Should the `println` calls be replaced with something like [timbre](https://github.com/ptaoussanis/timbre)'s debug logging?

**Comment by tatut** [comment]
I added a note about chrome_test to README. I'm closing this issue.
